_target_: weavenet.criteria.CriteriaStableMatching

loss_one2one: correlation
one2one_weight: 1.0 # constraint to be one-to-one matching  
stability_weight: 0.7 # constraint to be stable matching (with one2one_weight together).
gate_fairness_loss: false
fairness_weight: 0.01

fairness: null # null | sexequality | egalitarian | balance
