_target_: src.models.weavenet_module.WeaveNetLitModule

defaults:
    - _self_

  
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  betas: [0.9,0.999]
#  weight_decay: 0.0

scheduler: null
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 10

net:
  _target_: src.models.components.weavenet.WeaveNet
  head: 
      _target_: src.models.components.weavenet.WeaveNetHead
      input_channel: 2
      mid_channels: [64, 64, 64, 64, 64, 64]
      output_channels: [32, 32, 32, 32, 32, 32]
      calc_residual: null
      keep_first_var_after: 0
  output_channels: 1
  stream_aggregator:
      _target_: src.models.components.layers.DualSoftmaxSqrt
      
criteria:
    _target_: src.models.components.criteria.CriteriaStableMatching

    loss_one2one: correlation
    one2one_weight: 1.0 # constraint to be one-to-one matching  
    stability_weight: 0.7 # constraint to be stable matching (with one2one_weight together).

    fairness: null # null | sexequality | egalitarian | balance
    fairness_weight: 0.001 # ignored if fairness is null.
    gate_fairness_loss: false
