_target_: src.models.weavenet_module.WeaveNetLitModule

defaults:
    - _self_
    - net: weavenet_dense
    - criteria: default

do_jit_scripting: true

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  betas: [0.9,0.999]
#  weight_decay: 0.0

scheduler: null
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 10
