  _target_: weavenet.model.WeaveNetHead
  input_channels: 2
  output_channels_list: [32, 32, 32, 32, 32, 32]
  mid_channels_list: [64, 64, 64, 64, 64, 64]
  calc_residual: null
  keep_first_var_after: 0
  exclusive_elements_of_unit: 'none' # 'none'|'normalizer'|'all' for standard|bias-remove|dual weavenet.
  is_single_stream: true

