_target_: weavenet.model.TrainableMatchingModule
net: 
  _target_: weavenet.model.WeaveNet
  input_channels: 2
  output_channels_list: [32, 32, 32, 32, 32, 32]
  mid_channels_list: [64, 64, 64, 64, 64, 64]
  calc_residual: null
  keep_first_var_after: 0
  exclusive_elements_of_unit: 'none' # 'none'|'normalizer'|'all' for standard|bias-remove|dual weavenet.
  is_single_stream: false

output_channels: 1
stream_aggregator:
  _target_: weavenet.layers.DualSoftmaxSqrt
